directories:
  output: release
  buildResources: build
appId: com.greenpharm.app
productName: GreenPharm
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target: nsis
electronVersion: 44.1.1
