/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as GreenComputingRouteImport } from './routes/green-computing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SuppliersRouteImport } from './routes/suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenComputingRoute = GreenComputingRouteImport.update({
  id: '/green-computing',
  path: '/green-computing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expiry': typeof ExpiryRoute
  '/green-computing': typeof GreenComputingRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expiry': typeof ExpiryRoute
  '/green-computing': typeof GreenComputingRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expiry': typeof ExpiryRoute
  '/green-computing': typeof GreenComputingRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/expiry'
    | '/green-computing'
    | '/inventory'
    | '/notifications'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expiry'
    | '/green-computing'
    | '/inventory'
    | '/notifications'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/expiry'
    | '/green-computing'
    | '/inventory'
    | '/notifications'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExpiryRoute: typeof ExpiryRoute
  GreenComputingRoute: typeof GreenComputingRoute
  InventoryRoute: typeof InventoryRoute
  NotificationsRoute: typeof NotificationsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-computing': {
      id: '/green-computing'
      path: '/green-computing'
      fullPath: '/green-computing'
      preLoaderRoute: typeof GreenComputingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExpiryRoute: ExpiryRoute,
  GreenComputingRoute: GreenComputingRoute,
  InventoryRoute: InventoryRoute,
  NotificationsRoute: NotificationsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
